defaults:
  - base_model

output_modules:
  - _target_: schnetpack.atomistic.DipoleMoment
    n_in: ${model.representation.n_atom_basis}
    return_charges: True
    n_layers: 1
    init_zero: True
    module_dim : True
  - _target_: schnetpack.atomistic.ElectrostaticEnergy
  - _target_: schnetpack.atomistic.D4DispersionEnergy
  - _target_: schnetpack.atomistic.ZBLRepulsionEnergy
  - _target_: schnetpack.atomistic.Aggregation
  - _target_: schnetpack.atomistic.Atomwise
    output_key: ${property}
    n_in: ${model.representation.n_atom_basis}
    aggregation_mode: sum
    module_dim: True
    physnet_energy: True
    n_layers: 1
    init_zero: True

outputs:
  - _target_: schnetpack.atomistic.ModelOutput
    name: ${property}
    loss_fn:
      _target_: torch.nn.MSELoss
    metrics:
      mae:
        _target_: torchmetrics.regression.MeanAbsoluteError
      mse:
        _target_: torchmetrics.regression.MeanSquaredError
    loss_weight: 1
