defaults:
  - base_model

output_modules:
  - _target_: schnetpack.atomistic.DipoleMoment
    n_in: ${model.representation.n_atom_basis}
    return_charges: True
    n_layers: 1
    output_init_zero: True
    sum_module_dim : True
  - _target_: schnetpack.atomistic.ElectrostaticEnergy
    output_key: electrostatic
  - _target_: schnetpack.atomistic.D4DispersionEnergy
    output_key: dispersion
  - _target_: schnetpack.atomistic.ZBLRepulsionEnergy
    output_key: zbl
  - _target_: schnetpack.atomistic.Atomwise
    output_key: short_range
    n_in: ${model.representation.n_atom_basis}
    aggregation_mode: sum
    sum_module_dim: True
    n_layers: 1
    output_init_zero: True
  - _target_: schnetpack.atomistic.Aggregation
    output_key: ${property}
    keys: [dispersion, electrostatic, zbl, short_range]

outputs:
  - _target_: schnetpack.atomistic.ModelOutput
    name: ${property}
    loss_fn:
      _target_: torch.nn.MSELoss
    metrics:
      mae:
        _target_: torchmetrics.regression.MeanAbsoluteError
      mse:
        _target_: torchmetrics.regression.MeanSquaredError
    loss_weight: 1
